apiVersion: v1
kind: Secret
metadata:
  name: "ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJSM2w0WlhJMU1UTTZaMmh3WDBwSWNWVXdjR1JxUVRKV1YxaEtORlJOYzFVM1VrSkxiR1EyTjI0M1p6SnhVa04wVHc9PSINCiAgICB9DQogIH0NCn0NCg=="
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
