apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJSM2w0WlhJMU1UTTZaMmh3WDBwSWNWVXdjR1JxUVRKV1YxaEtORlJOYzFVM1VrSkxiR1EyTjI0M1p6SnhVa04wVHc9PSINCiAgICB9DQogIH0NCn0NCg==
type: kubernetes.io/dockerconfigjson
